config/routes.rb
Rails.application.routes.draw do 
  get 'games', to:"games#index", as: :games
  get 'contact' ,to: "contact#index"
  get 'about', to: "about#index"

  get 'locus', to: "locus_blaster_page#game"
  get 'games/locus_blaster', to: "locus_blaster_page#game", as: :locus_blaster
  get 'games/kingdoms&cards', to: "kingdoms_and_cards#game", as: :kingdoms_and_cards

  get 'privacy_policy',to:'privacy_policy#index'

  match '*path', to: 'application#render_404', via: :all
  

  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
    layout "error"
  
    def show
      @exception = request.env["action_dispatch.exception"]
      @status_code = @exception.try(:status_code) ||
                     ActionDispatch::ExceptionWrapper.new(
                      request.env, @exception
                    ).status_code
  
      render view_for_code(@status_code), status: @status_code
    end
  
    private
      def view_for_code(code)
        supported_error_codes.fetch(code, "500",)
      end
  
      def supported_error_codes
        {
          403 => "403",
          404 => "404",
          500 => "500"
        }
      end
  end
  

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/kingdoms_and_cards_controller.rb
class KingdomsAndCardsController < ApplicationController
    def game
    end
end

app/controllers/locus_blaster_page_controller.rb
class LocusBlasterPageController < ApplicationController
    def index
    end
end

app/controllers/privacy_policy_controller.rb
class PrivacyPolicyController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

    def default_meta_tags
        {
          site: 'danodin.com',
          title: 'Dan Odin Games',
          reverse: true,
          separator: '|',
          description: 'Dan Odin — Game Developer based in Lagos Nigeria; With the long term vision of exposing Africa\'s rich stories to the world through video games and to become the greatest game developer in Africa.',
          keywords: 'Game Developer, Lagos, Nigeria, Africa\'s Rich Stories, Video Games, African Game Developer, African Video Games, Game Development in Africa, Game Development Vision, Game Developer Portfolio, Africa\'s Gaming Industry, Game Design, African Gaming Culture, Storytelling in Video Games, African Game Narrative, Game Development Expertise, African Game Studio , Nigerian Game Studio, Lagos Based Studio',
          canonical: request.original_url,
          noindex: !Rails.env.production?,
          icon: [
            { href: image_url('favicon.png') },
            { href: image_url('panda_with_shades_and_moon.png'), rel: 'apple-touch-icon', sizes: '180x180', type: 'image/png' },
          ],
          og: {
            site_name: 'danodin.com',
            title: 'Dan Odin Games',
            description: 'Dan Odin — The Best Game Developer based in Lagos Nigeria, Africa ', 
            type: 'website',
            url: request.original_url,
            image: image_url('ddpg_so_cute.png')
          }
        }
      end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/kingdoms_and_cards_helper.rb
module KingdomsAndCardsHelper
end

app/helpers/locus_blaster_page_helper.rb
module LocusBlasterPageHelper
end

app/helpers/privacy_policy_helper.rb
module PrivacyPolicyHelper
end

app/views/contact/index.html.erb
<% set_meta_tags title: 'Contact Dan Odin', description: 'ʕ⁠·⁠ᴥ⁠·⁠ʔ For Business, Press, Privacy Policy or you need Support for one of my games' %>


<div class="container lg:px-72 pb-16 mx-auto text-center  my-12 bg-pandablack text-white shadow-md rounded-lg">
  <h2 class="text-2xl font-semibold mb-4">CONTACT ME</h2>
  

  <p class="my-4">For Business, Press, Privacy Policy or you need Support for one of my games</p>
  <hr class="my-2 border-t-1 border-gray-400">

  <a href="mailto:danphilodin@gmail.com" class="my-4 text-white underline font-bold ">Send Email</a>
  <hr class="my-2 border-t-1 border-gray-400">

  <p class="my-4">I check my emails every 6 am, 12 pm, 6 pm WAT.</p>


  <p class="my-4">If it is really <i><b>urgent</b></i>, contact me on Telegram</p>
  <hr class="my-2 border-t-1 border-gray-400">
  <a href="https://t.me/DanOdin" class="text-white underline font-bold"> Send Direct Message</a>
  <hr class="my-2 border-t-1 border-gray-400">

  <p class="mt-4">Go through the anti-spam screening, After which I will reply in minutes.</p>
</div>

app/views/games/index.html.erb
<% set_meta_tags title: 'Games Page', description: 'Dan Odin\'s Games ʕ⁠·⁠ᴥ⁠·⁠ʔ.. Locus Blaster | Kingdoms & Cards ' %>
 
<div class="grid grid-cols-1 gap-10 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 mx-auto pb-24">
  <div class="max-w-sm bg-pandablack border border-gray-200 rounded-lg shadow">
    <a href="">
      <%= image_tag "locus_icon.png", class:"rounded-t-lg", alt:"locus blaster icon"%>
    </a>
    <div class="p-5">
     <div class="flex items-center justify-between"> <a href="">
        <h5 class="mb-2 text-3xl font-bold tracking-tight text-pandawhite">LOCUS BLASTER</h5>
      </a><a href="" class="bg-pandablack hover:bg-pandablue text-pandawhite text-sm font-medium mr-2 px-2.5 py-0.5 rounded   border border-pandawhite inline-flex items-center justify-center">BETA 2.2</a></div>
      <p class="mb-3 font-normal text-gray-400">Enter Into LOCUS, Destroy Enemy spaceships and become THE Space God In this free to play 3D Arcade space shooter with a retro vibe.</p>
      <div>
     <%= link_to "Learn More", locus_blaster_path, class:"inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-pandablue rounded-lg  focus:ring-2 focus:outline-none focus:ring-pandawhite"%>

      </div>
    </div>
  </div>

  <div class="max-w-sm bg-pandablack border border-gray-200 rounded-lg shadow">
    <a href="">
      <%= image_tag "king_dom.png", class:"rounded-t-lg", alt:"Panda with moon"%>
    </a>
    <div class="p-5">
      <div class="flex items-center justify-between"> <%= link_to "KINGDOMS & CARDS", "", class:"mb-2 text-2xl font-bold tracking-tight text-pandawhite"%> 
      
      <a href="" class="bg-pandablack hover:bg-pandablue text-pandawhite text-sm font-medium mr-2 px-2.5 py-0.5 rounded   border border-pandawhite inline-flex items-center justify-center">PROTOTYPE</a>
      
      </div>

      
      <p class="mb-3 font-normal text-gray-400">Immerse yourself in the ultimate fusion of this card/board game, inspired by the thrilling dynamics of rock-paper-scissors. </p>

      <div>
     <%= link_to "Learn More", kingdoms_and_cards_path, class:"inline-flex items-center px-3 py-2 text-sm font-medium text-center text-white bg-pandablue rounded-lg  focus:ring-2 focus:outline-none focus:ring-pandawhite"%>

      </div>
    </div>
  </div>
</div>

app/views/kingdoms_and_cards/game.html.erb
<% set_meta_tags title: 'Kingdoms & Cards', description: 'A card game of thrill, skill and luck | A protoypical version that can also pass off as a classic version of a unique card game that gets everyone on their toes! | Immerse yourself in the ultimate fusion of this card/board game, inspired by the thrilling dynamics of rock-paper-scissors. Prepare for conquest with three card types, KING, SOLDIER, CITIZEN. Each with their own dice-supported strength. ʕ⁠·⁠ᴥ⁠·⁠ʔ', keywords: 'Nigerian Game Developer,Card Game, Thrill, Skill, Luck, Unique Card Game, Classic Card Game, Board Game, Rock-Paper-Scissors, King Cards, Soldier Cards, Citizen Cards, Dice-Supported Strength, Prototype Card Game, Strategy Game, Card Game Conquest, Card Game Dynamics, Tabletop Game, Card Game Challenge, Exciting Gameplay, Immersive Experience, Gaming Fusion, Competitive Card Game' %>

<div class="flex flex-col gap-16 lg:gap-40 items-center">
    <section class="mx-auto  bg-gray-900 bg-[url('https://flowbite.s3.amazonaws.com/docs/jumbotron/hero-pattern-dark.svg')]">
        <div class="py-8 px-4 mx-auto max-w-screen-xl text-center lg:py-16 z-10 relative">
            <div class="flex mx-auto justify-center px-5 items-center">
                <a href="/kingdoms&cards" class="mx-auto">
                    <%= image_tag "king_dom.png", class:"rounded-t-lg rounded-b-lg w-28 h-28 rounded", alt:"locus blaster icon"%>
                </a>
            </div>
            <h1 class="mb-4 pt-6 text-4xl font-extrabold tracking-tight leading-none md:text-5xl lg:text-3xl text-white">Kingdoms <br>& Cards<br><span class="text-xl"><h3>[classic]</h3></span></h1>
            <p class="mb-8 text-lg font-normal  lg:text-xl sm:px-16 lg:px-48 text-gray-200">A card game of thrill, skill and luck.</p>
           <div class=" inline-flex  justify-evenly gap-8">
           

            <a href="https://danodin.itch.io/kingdoms-cards" target="_blank"><%= image_tag "https://cdn-eu.icons8.com/4-KnR6g-MES0hPuopQkZ0A/N0U21te86kSoeKL0_NALGQ/Group_2.png", class:"w-10 h-10"%></a>

       
            
            </div>
        </div>
        <div class="bg-gradient-to-b  from-green-900 to-transparent w-full h-full absolute top-0 left-0 z-0"></div>
    </section>
    <section class="flex-grow overflow-auto pb-64">
        <div class="flex justify-center items-center mx-auto lg:px-48"> 
            <div class="text-left p-4">

             <div class="py-6">
     
  


            <a href="#" class="bg-red-500 hover:bg-pandablue text-pandawhite text-sm font-medium mr-2 px-2.5 py-0.5 rounded   border border-pandawhite inline-flex items-center justify-center">Protoype</a> 


            <a href="#" class="bg-pandablack hover:bg-pandablue text-pandawhite text-sm font-medium mr-2 px-2.5 py-0.5 rounded   border border-pandawhite inline-flex items-center justify-center">Strategy</a>  

            <a href="#" class="bg-pandablack hover:bg-pandablue text-pandawhite text-sm font-medium mr-2 px-2.5 py-0.5 rounded   border border-pandawhite inline-flex items-center justify-center">Card Game</a> 

        </div>

            <div class="py-10 flex flex-row justify-between ">

            <p><strong >Kingdoms & Cards [classic]</strong></p>
         </div>
        
    <div class="py-6">
                <p>
    A protoypical version that can also pass off as a classic version of a unique card game that gets everyone on their toes!
</p><br>

<div class="py-10">
        <p><strong >AVAILABLE FOR</strong></p>
    </div>


<a href="#" class="bg-pandablack hover:bg-pandablue text-pandawhite text-sm font-medium mr-2 px-2.5 py-0.5 rounded   border border-pandawhite inline-flex items-center justify-center">WINDOWS</a>

<a href="#" class="bg-pandablack hover:bg-pandablue text-pandawhite text-sm font-medium mr-2 px-2.5 py-0.5 rounded   border border-pandawhite inline-flex items-center justify-center">LINUX</a>
    <div class="py-10">
        <p><strong >GAMEPLAY</strong></p>
    </div>
<p>
    Immerse yourself in the ultimate fusion of this card/board game, inspired by the thrilling dynamics of rock-paper-scissors. Prepare for conquest with three card types, KING, SOLDIER, CITIZEN. Each with their own dice-supported strength.
</p>

<p>
   Strategize wisely, sacrificing cards to secure victory in the final rounds with lady luck on your side you'll be unstoppable. Are you ready to dominate?
</p>

<br>
    <div class="py-10">
        <p><strong >FEATURES</strong></p>
    </div>
<ul>
    <li><b class="text-lg">Hybrid Game Mechanics</b>: This card game is a fusion of rock paper scissors where rock is king, scissors is soldier and paper is citizen. Having taken from the Mechanics of rock paper scissors a fun dynamic and unique card game has been created that can be played by anyone. </li><br>

    <li><b class="text-lg">Strategize or Lean on Luck</b>: How ever you play is up to you, there are no strict rules.</li><br>

    <li><b class="text-lg">Easy To Learn</b>: Having in mind the principles that guides Kingdoms and Cards, You should be able to pick it up by playing it now! </li>
</ul>

<div class="py-10">
        <p><strong >SCREENSHOTS</strong></p>
    </div>
        



        
<div id="gallery" class="relative w-full" data-carousel="slide">

    <div class="relative h-56 overflow-hidden rounded-lg md:h-96">
         <!-- Item 1 -->
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
            <%= image_tag "kc_sc/sc1.png", class:"absolute block max-w-full  rounded-lg md:h-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"%>
        </div>
        <!-- Item 2 -->
        <div class="hidden duration-700 ease-in-out" data-carousel-item="active">
                        <%= image_tag "kc_sc/sc2.png", class:"absolute block max-w-full  rounded-lg md:h-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"%>
        </div>
        <!-- Item 3 -->
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
                       <%= image_tag "kc_sc/sc3.png", class:"absolute block max-w-full  rounded-lg md:h-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"%>
        </div>
        <!-- Item 4 -->
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
                        <%= image_tag "kc_sc/sc4.png", class:"absolute block max-w-full  rounded-lg md:h-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"%>
        </div>
        <!-- Item 5 -->
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
                        <%= image_tag "kc_sc/sc5.png", class:"absolute block max-w-full   rounded-lg md:h-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"%>
        </div>
        <!-- Item 6 -->
        <div class="hidden duration-700 ease-in-out" data-carousel-item>
                        <%= image_tag "kc_sc/sc6.png", class:"absolute block max-w-full   rounded-lg md:h-full -translate-x-1/2 -translate-y-1/2 top-1/2 left-1/2"%>
        </div>
    </div>
    <!-- Slider controls -->
    <button type="button" class="absolute top-0 left-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-prev>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-gray-800/30  group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-4 h-4 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 1 1 5l4 4"/>
            </svg>
            <span class="sr-only">Previous</span>
        </span>
    </button>
    <button type="button" class="absolute top-0 right-0 z-30 flex items-center justify-center h-full px-4 cursor-pointer group focus:outline-none" data-carousel-next>
        <span class="inline-flex items-center justify-center w-10 h-10 rounded-full bg-gray-800/30 group-hover:bg-gray-800/60 group-focus:ring-4 group-focus:ring-white group-focus:ring-gray-800/70 group-focus:outline-none">
            <svg class="w-4 h-4  text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 6 10">
                <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 9 4-4-4-4"/>
            </svg>
            <span class="sr-only">Next</span>
        </span>
    </button>
</div>

    



    <div class="py-10">
        <p><strong >GET IT NOW</strong></p>

    </div>
     <div class=" inline-flex  justify-evenly gap-20">
            

            <a href="https://danodin.itch.io/kingdoms-cards" target="_blank"> <%= image_tag "https://cdn-eu.icons8.com/4-KnR6g-MES0hPuopQkZ0A/N0U21te86kSoeKL0_NALGQ/Group_2.png", class:"w-10 h-10"%></a>

           
           
            
    </div><br>
     <div class=" inline-flex justify-evenly gap-7">
           

            <p>ITCH.IO</P>

            
    </div>
    <div class="bg-black shadow-inner  shadow-green-700 rounded-lg p-6 mt-10">
    <div class="py-10">
        <p><strong >DEV NOTE</strong></p>

        <div class=" inline-flex justify-evenly gap-7">
           

            <p>This game is being developed and is in need of funding thus development might be slow. <%= link_to " Contact me", contact_path, class:"underline" %> for further questions if any.</P>

            

            
    </div>
    <br>
    <br>
    <a href="https://www.buymeacoffee.com/danodin69" class="inline-flex items-center  px-5 py-5 text-sm font-medium text-center text-white bg-transparent rounded-lg shadow-inner  shadow-green-700  focus:ring-2 focus:outline-none focus:ring-pandawhite">

                <span class="h-5"><%= image_tag "bmc.png", class:" h-8 mr-3"%></span>
               

                Buy me Cocaine - *A Coffee

            </a>
<br>
<br>

    <a href="https://paystack.com/pay/danodin" class="inline-flex items-center  px-5 py-5 text-sm font-medium text-center text-pandawhite  bg-transparent shadow-inner  shadow-green-700 rounded-lg  focus:ring-2 focus:outline-none focus:ring-pandawhite ">

                <span class="h-5"><%= image_tag "paystack.png", class:" h-5 mr-3"%>
                
                </span>
                Support as You like - Paystack

            </a>
    </div>
    </div>
            </div>
        </div>


    </section>
</div>

app/views/layouts/error.html.erb
<%# app/views/layouts/error.html.erb %>

<!DOCTYPE html>
<html>
  <head>
    <%= render "layouts/head" %>
  </head>

  <body>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/privacy_policy/index.html.erb
<% set_meta_tags title: 'Privacy Policy', description: ' Boring Legal stuff, ain\'t reading allat. ʕ⁠·⁠ᴥ⁠·⁠ʔ' %>

<div class="pb-28 mx-auto"><div class="max-w-xl mx-auto mt-8 p-6 pb-16 -mb-16 lg:max-w-2xl text-pandawhite shadow-md rounded-lg text-left">
  <h2 class="text-2xl font-semibold mb-4">PRIVACY POLICY</h2>
  <hr class="my-2 border-t-2 border-gray-400">

  <p class="mb-4">Dan Odin Games</p>
  

  <p class="mb-4">Last updated: June 16, 2023</p>
  
  <P class="mb-4">Dan Odin Games, operated solely by [Dan Odin], collects and processes personal information as described in this privacy policy.</p>

  <p class="mb-4">Dan Odin Games ("us", "we", or "our") operates www.danodin.com (the "Site"). This page informs you of our policies regarding the collection, use, and disclosure of Personal Information we receive from users of the Site.</p>
  

  <p class="mb-4">We use your Personal Information only for providing and improving the Site. By using the Site, you agree to the collection and use of information in accordance with this policy.</p>
  

  <p class="mb-4"><strong>Information Collection and Use</strong></p>
  

  <p class="mb-4">While using our Site, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to, your name, email address, postal address, and phone number ("Personal Information").</p>
  

  <p class="mb-4"><strong>Log Data</strong></p>
  

  <p class="mb-4">Like many site operators, we collect information that your browser sends whenever you visit our Site ("Log Data"). This Log Data may include information such as your computer's Internet Protocol ("IP") address, browser type, browser version, the pages of our Site that you visit, the time and date of your visit, the time spent on those pages, and other statistics.</p>
  

  <p class="mb-4"><strong>Communications</strong></p>
  

  <p class="mb-4">We may use your Personal Information to contact you with newsletters, marketing, or promotional materials and other information that relates to our services. You can opt-out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>
  

  <p class="mb-4"><strong>Cookies</strong></p>
  

  <p class="mb-4">Cookies are files with small amounts of data, which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your computer's hard drive.</p>
  

  <p class="mb-4">Like many sites, we use "cookies" to collect information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Site.</p>
  

  <p class="mb-4"><strong>Advertising</strong></p>
  

  <p class="mb-4">Our Site may display ads from third-party ad networks. These ads may collect data about your browsing behavior and interests to serve you more relevant ads. Please note that we are not responsible for the data collected by these ad networks. Your interaction with those ads is subject to the privacy policies of the respective ad networks.</p>
  

  <p class="mb-4"><strong>Security</strong></p>
  

  <p class="mb-4">The security of your Personal Information is important to us, but remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. While we strive to use commercially acceptable means to protect your Personal Information, we cannot guarantee its absolute security.</p>
  

  <p class="mb-4"><strong>Changes to This Privacy Policy</strong></p>
  

  <p class="mb-4">This Privacy Policy is effective as of June 16, 2023, and will remain in effect except with respect to any changes in its provisions in the future, which will be in effect immediately after being posted on this page.</p>
  

  <p class="mb-4">We reserve the right to update or change our Privacy Policy at any time, and you should check this Privacy Policy periodically. Your continued use of the Service after we post any modifications to the Privacy Policy on this page will constitute your acknowledgment of the modifications and your consent to abide and be bound by the modified Privacy Policy.</p>
  

  <p class="mb-4"><strong>Contact Us</strong></p>
  

  <p class="mb-4">If you have any questions about this Privacy Policy, please <span><%=link_to "send a message", contact_path, class:"underline"%></span></p>
</div>
</div>

app/views/shared/_footer.html.erb
<footer class="fixed bottom-0 left-0 z-20 w-full p-1 bg-pandablack border-t border-pandablue shadow md:flex md:items-center md:justify-between md:p-2 ">
    <ul class="flex flex-wrap justify-center items-center mt-3 text-sm font-medium text-pandawhite sm:mt-0">
        <li>
            <%= link_to "PRIVACY-POLICY", privacy_policy_path,class:"mr-4 hover:underline md:pb-10 md:mr-6" %>
        </li>
    </ul>
    <div class="flex flex-wrap justify-center">
    <span class=" text-sm text-pandawhite sm:text-center p-2">©<a href="/" class="hover:underline"><b>Dan Odin </b> </a> All Rights Reserved.
    </span></div>
    
</footer>

app/views/shared/_navbar.html.erb
<nav class="bg-pandablack fixed w-full z-20 top-0 left-0">
  <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto py-5">
   <button data-collapse-toggle="navbar-sticky" type="button" class="mobile-menu-button inline-flex items-center p-2 w-10 h-10 justify-center text-sm text-gray-500 rounded-lg md:hidden hover:bg-pandablue focus:outline-none focus:ring-1 focus:ring-pandablue" aria-controls="navbar-sticky" aria-expanded="false">
        <span class="sr-only">Open main menu</span>
        <img src="https://cdn-eu.icons8.com/4-KnR6g-MES0hPuopQkZ0A/dvbdz_EP2UWlKa3z4jMJng/Group_4_Copy.png">
    </button>
  <a href="/" class="flex items-center">
      <%= image_tag "solo.png", class:"h-10 mr-3", alt:"Panda with moon"%>
      <span class="self-center lg:pr-28  whitespace-nowrap  h-5"><%= image_tag "dan_odin_text.png", class:"h-5", alt:"Dan Odin"%></span>
  </a>

  
  <div class="flex md:order-2 text-sm flex-row  p-4  md:p-2 mt-0 md:flex-row md:space-x-8 md:mt-0 md:border-0">
  
      <ul>
        <a href="https://t.me/danodin69" target="_blank" > <img src="https://cdn-eu.icons8.com/4-KnR6g-MES0hPuopQkZ0A/OBX6WZ9iEUe4VuOVec2mjg/Shape.png" class="h-4 mr-3" alt="Telegram" /></a>
      </ul>

      <ul>
        <a href="https://x.com/danodin69" target="_blank" > <img src="https://cdn-eu.icons8.com/NHMmJHh_t0yJXMu187dH5A/xs2wK4xtfESh-RADQoQgtw/Twitterx.png" class="h-5 mr-3" alt="X.com" /></a>
      </ul>

      <ul>
        <a href="https://instagram.com/danodin69"target="_blank" > <img src="https://cdn-eu.icons8.com/4-KnR6g-MES0hPuopQkZ0A/8-DdIX5n1k6JWDW32qw23g/Shape.png" class="h-4 mr-3" alt="Instagram" /></a>
      </ul>

      <ul>
        <a href="https://github.com/danodin69" target="_blank" > <img src="https://cdn-eu.icons8.com/4-KnR6g-MES0hPuopQkZ0A/8kOLgUwe1U2e2oQnqkRYXg/Shape.png" class="h-4 mr-3" alt="GitHub" /></a>
      </ul>

     
  </div>
  <div class="items-center justify-between hidden mobile-menu w-full md:flex md:w-auto md:order-1" id="navbar-sticky">
    <ul class="flex flex-col p-4 md:p-0 mt-4 font-semibold text-1xl lg:text-1xl md:flex-row md:space-x-8 md:mt-0 md:border-0 ">
      <li>
        <%= link_to "GAMES",games_path, class:"block py-2 pl-3 pr-4 text-pandawhite rounded md:bg-transparent md:p-0 hover:bg-pandablue md:hover:bg-transparent md:hover:text-pandablue"%>
      </li>
     <li>
        <%= link_to "ABOUT",about_path, class:"block py-2 pl-3 pr-4 text-pandawhite rounded md:bg-transparent md:p-0 hover:bg-pandablue md:hover:bg-transparent md:hover:text-pandablue"%>
      </li>
      <li>
        <%= link_to "CONTACT",contact_path, class:"block py-2 pl-3 pr-4 text-pandawhite rounded md:bg-transparent md:p-0 hover:bg-pandablue md:hover:bg-transparent md:hover:text-pandablue"%>
      </li>

      
    </ul>
  </div>
  </div>
    <script>
	    const btn = document.querySelector("button.mobile-menu-button");
	    const menu = document.querySelector(".mobile-menu");

	    btn.addEventListener("click", () => {
	    menu.classList.toggle("hidden");
	  });
</script>
</nav>